project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Jen (Andy) Chuang"
  navbar:  
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

