project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Jen Chuang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: full
    
editor: visual

