project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Jen (Andy) Chuang"
  navbar:  
    background: primary
    left:
      - href: index.qmd
        text: Home
      - research.qmd
#      - teaching.qmd
      - cv.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    page-layout: full
    fontcolor: black
    mainfont: "Gill Sans"
    fontsize: 1.25rem
    line-height: 160%;


    
editor: visual

